config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
  
    #Si escribe aquí todas las configuraciones de URL para la aplicación nagoyameshi, será difícil de leer.
    #Leer nagoyameshi.urls al acceder a la página superior
 
    path("", include("nagoyameshi.urls")),

    # URL設定 ↓URL        ↓呼び出す処理        accounts/にアクセスした時、allauthのurls.pyを呼び出す。
    path('accounts/', include('allauth.urls')),

]

nagoyameshi/urls.py
from django.urls import path

# views.pyをimportする。
from nagoyameshi import views



app_name    = "nagoyameshi"
urlpatterns = [
    path("", views.index, name="index"),
    path("restaurant/<int:pk>/", views.restaurant, name="restaurant" ),
    #             ↑ <int:pk> は int型(整数型)の場合、整数をpkとして扱う。このpkをビューに引き渡す。
    # restaurant/1/ や restaurant/3/ 
    path("review/", views.review, name="review"),
    path("favorite/", views.favorite, name="favorite"),
    path("reservation/",views.reservation, name="reservation"),
    
    path("mypage/", views.mypage, name="mypage"),
  
    # レビューの削除と編集を追加する。
    path("review_edit/<int:pk>/", views.review_edit, name="review_edit" ),
    path("review_delete/<int:pk>/", views.review_delete, name="review_delete" ),


    # 予約キャンセルのURL設定を追加
    path("reservation_cancel/<int:pk>/", views.reservation_cancel, name="reservation_cancel" ),

    # Stripeのセッションを作る checkout 
    path("checkout/", views.checkout, name="checkout"),
    
    # Stripeのセッション(支払い)を確認する success
    path("success/", views.success, name="success"),

    # サブスクリプションの操作
    path("portal/", views.portal, name="portal"),


]

nagoyameshi/models.py
from django.db import models

# Create your models here.
# models.py → admin.py → views.py → urls.py → templates 

# Djangoの中にあるデフォルトのユーザーモデル。
# python manage.py createsuperuser このコマンドでUserモデルにデータが追加される。
from django.contrib.auth import get_user_model
User = get_user_model()
# これがER図の会員の部分になる。
from django.utils import timezone 

# 追加のバリデーションを実装する
from django.core.exceptions import ValidationError



class Category(models.Model):

    name        = models.CharField(verbose_name="名前", max_length=15)
    created_at  = models.DateTimeField(verbose_name="作成日時", default=timezone.now)
    updated_at  = models.DateTimeField(verbose_name="更新日時", auto_now=True)

    def __str__(self):
        return self.name

    def str_id(self):
        return str(self.id)
    




class Restaurant(models.Model):

    category        = models.ForeignKey(Category, verbose_name="カテゴリ", on_delete=models.CASCADE)

    name            = models.CharField(verbose_name="名前", max_length=50)
    # ImageField で画像の保存ができる。(アップロード先のパスを指定。)
    image           = models.ImageField(verbose_name="画像", upload_to="nagoyameshi/restaurant/image/")
    # DBに保存されるのは、画像ではなく、画像の保存先のパス(文字列)
    # 画像本体はプロジェクトディレクトリのmediaディレクトリに保存する。(settings.pyで設定)

    description     = models.CharField(verbose_name="店舗説明", max_length=500)

    # 時刻だけを入力するフィールド 10:00 ~ 22:00 の場合、 start_at に10:00　、 end_at に 22:00 
    start_at        = models.TimeField(verbose_name="営業開始時間",default=timezone.now)
    end_at          = models.TimeField(verbose_name="営業終了時間",default=timezone.now)
    
    cost            = models.PositiveIntegerField(verbose_name="価格帯")



    # 111-1111 などとハイフンを含める場合、文字列型で8文字までとする。
    post_code       = models.CharField(verbose_name="郵便番号", max_length=8)

    # 住所は文字列型。
    address         = models.CharField(verbose_name="住所", max_length=100)


    # 電話番号は0から始まるので、数値型ではなく文字列型で。
    # 携帯電話番号であれば11桁、固定回線の場合は10桁 混乱を招くためハイフンを除外する。
    tel             = models.CharField(verbose_name="電話番号", max_length=11)


    # 計算をしないのであれば、数値ではなく文字列で。


    # 定休日は必須には含まれず、多対多を知る必要があるため、一旦除外
    #holiday         = models.ManyToManyField(Holiday, verbose_name="定休日")
    # 店舗Aは、火曜と木曜が休み
    # 店舗Bは、火曜と土曜が休み
    # 店舗Cは、月曜と土曜と日曜が休み
    # 店舗ごとに曜日を複数指定する。

    created_at      = models.DateTimeField(verbose_name="投稿日時", default=timezone.now)
    updated_at      = models.DateTimeField(verbose_name="更新日時", auto_now=True)


# 星のレビュー
# https://noauto-nolife.com/post/django-star-review/
#from django.core.validators import MinValueValidator,MaxValueValidator

#MAX_STAR      = 5


class Review(models.Model):

    restaurant  = models.ForeignKey(Restaurant, verbose_name="店舗", on_delete=models.CASCADE)
    user        = models.ForeignKey(User, verbose_name="投稿者", on_delete=models.CASCADE)
    

    #star        = models.IntegerField(verbose_name="星",validators=[MinValueValidator(1),MaxValueValidator(MAX_STAR)],default=1)
    content     = models.CharField(verbose_name="内容", max_length=100)

    created_at  = models.DateTimeField(verbose_name="投稿日時", default=timezone.now)
    updated_at  = models.DateTimeField(verbose_name="更新日時", auto_now=True)


    # 星のレビューの表示で使う
    # Se utiliza para mostrar reseñas de estrellas
    """
    def star_icon(self):
        dic               = {}
        dic["true_star"]  = self.star * " "
        dic["false_star"] = ( MAX_STAR - self.star) * " "

        return dic
    """



class Favorite(models.Model):
    """
    #同一ユーザーが複数回同じレストランをお気に入り登録できないように設定する（重複を防ぐ）
    class Meta:
        unique_together=("user","restaurant")
    """

    user       = models.ForeignKey(User, verbose_name="登録者",on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, verbose_name="店舗",on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name="作成日時", default=timezone.now)



class Reservation(models.Model):
    user            = models.ForeignKey(User, verbose_name="予約者", on_delete=models.CASCADE)
    restaurant      = models.ForeignKey(Restaurant, verbose_name="店舗", on_delete=models.CASCADE)

    datetime        = models.DateTimeField(verbose_name="予約日時")
    headcount       = models.PositiveIntegerField(verbose_name="人数")

    created_at  = models.DateTimeField(verbose_name="投稿日時", default=timezone.now)
    updated_at  = models.DateTimeField(verbose_name="更新日時", auto_now=True)


    # TODO: 追加のバリデーションを用意する。


    def clean(self):
        super().clean()

        # TODO:ここに追加のバリデーションの処理を書く


        # 予約日時が今日よりも未来であるか？
        # 今日よりも過去の予約日時を指定している場合は、バリデーションエラー
        if timezone.now() > self.datetime:
            raise ValidationError("予約日時が今日よりも過去になっています。")
            

        # 予約日時が営業時間内であるか？
        print( self.datetime.time() )
        print( self.restaurant.start_at )
        print( self.restaurant.end_at )

        if self.datetime.time() < self.restaurant.start_at or self.restaurant.end_at < self.datetime.time():
            raise ValidationError("予約日時が営業時間外になっています。")




# Un modelo para distinguir entre miembros pagos y miembros gratuitos.
class PremiumUser(models.Model):
    user            = models.ForeignKey(User, verbose_name="予約者", on_delete=models.CASCADE)
    # TextFieldは文字数の制限がないフィールド
    premium_code    = models.TextField(verbose_name="有料会員コード")

nagoyameshi/forms.py
from django import forms 

# Reviewを元にバリデーションルールを作る
# Crear reglas de validación basadas en reseñas
from .models import Review,Favorite,Reservation

class ReviewForm(forms.ModelForm):
    class Meta:
        model   = Review
        fields  = ["user","restaurant","content"]

# Favoriteを元にバリデーションルールを作る
# Crear reglas de validación basadas en Favoritos
class FavoriteForm(forms.ModelForm):
    class Meta:
        model   = Favorite
        fields  = ["user","restaurant"]


class ReservationForm(forms.ModelForm):
    class Meta:
        model   = Reservation
        fields  = ["user","restaurant", "datetime","headcount"]




"""
from .models import Topic

# Topicモデルを元にして作ったバリデーションルール(フォームクラス)
class TopicForm(forms.ModelForm):

    class Meta:
        model   = Topic
        fields  = [ "comment" ]
"""

nagoyameshi/views.py
from django.shortcuts import render, redirect

from django.views import View

# クエリビルダ
from django.db.models import Q


# models.py の中の Restaurant クラスをimportするには？
#from .models import Restaurant

# models.py の中の Category クラスをimportするには？
#from .models import Category

# ↑2つは ↓ 1つで書ける
from .models import Restaurant, Category, Review, Favorite, Reservation, PremiumUser

# forms.pyから ReviewFormをimportする。
from .forms import ReviewForm,FavoriteForm,ReservationForm


# トップページで一覧表示をするビュー
# index.htmlをレンダリングするビューを作る

# ビューに多重継承させることで、ログイン状態をチェックして、未ログインであればログインページ( accounts/login/ )へリダイレクトできる。
from django.contrib.auth.mixins import LoginRequiredMixin

from django.utils import timezone


# == stripe ==
# settings.pyを読み込み
from django.conf import settings
# URLを作る。
from django.urls import reverse_lazy

# pip install stripe 
import stripe
# settings.pyのAPIキーをセットする。
stripe.api_key  = settings.STRIPE_API_KEY

# 2: Stripeにセッションを作ってもらう
# Stripeに対してセッションを作ってくれと依頼をするビュー。
class CheckoutView(LoginRequiredMixin,View):
    def post(self, request, *args, **kwargs):

        #  ↓3: セッションを作った   ↓ 2: セッションを作る
        checkout_session = stripe.checkout.Session.create(
            line_items=[
                {
                    'price': settings.STRIPE_PRICE_ID,
                    'quantity': 1,
                },
            ],
            payment_method_types=['card'],
            mode='subscription',

            # 6 で Stripeがカードで支払い成功したときのURL。クライアントがカードを入力せずにキャンセルしたときのURL
            success_url=request.build_absolute_uri(reverse_lazy("nagoyameshi:success")) + '?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=request.build_absolute_uri(reverse_lazy("nagoyameshi:mypage")),
            # 絶対パスのURLを作っている。 http から始まるURL
        )

        # セッションid
        print( checkout_session["id"] )

        # 4: 作ったセッションのURLヘリダイレクトする。
        return redirect(checkout_session.url)

checkout    = CheckoutView.as_view()


# 5: クライアントはStripeのサイトへ行き、カードを入力
# 6: Stripeはカードで支払い

# 7: Stripeは↓のビューへリダイレクト
class SuccessView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):


        # 8: DjangoはStripeへカードの支払いを確認する。

        # パラメータにセッションIDがあるかチェック
        if "session_id" not in request.GET:
            print("セッションIDがありません。")
            return redirect("nagoyameshi:index")


        # そのセッションIDは有効であるかチェック。
        try:
            checkout_session_id = request.GET['session_id']
            checkout_session    = stripe.checkout.Session.retrieve(checkout_session_id)
        except:
            print( "このセッションIDは無効です。")
            return redirect("nagoyameshi:index")

        print(checkout_session)

        # statusをチェックする。未払であれば拒否する。(未払いのsession_idを入れられたときの対策)
        if checkout_session["payment_status"] != "paid":
            print("未払い")
            return redirect("nagoyameshi:index")

        print("支払い済み")


        # 有効であれば、セッションIDからカスタマーIDを取得。ユーザーモデルへカスタマーIDを記録する。
        """
        request.user.customer   = checkout_session["customer"]
        request.user.save()
        """

        # PremiumUser を新規作成する。
        premium_user        = PremiumUser()
        premium_user.user   = request.user
        premium_user.premium_code = checkout_session["customer"]

        premium_user.save()

        print("有料会員登録しました！")

        return redirect("nagoyameshi:mypage")

success     = SuccessView.as_view()



# サブスクリプションの操作関係
class PortalView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        
        premium_user = PremiumUser.objects.filter(user=request.user).first()

        if not premium_user:
            print( "有料会員登録されていません")
            return redirect("nagoyameshi:index")

        # ユーザーモデルに記録しているカスタマーIDを使って、ポータルサイトへリダイレクト
        portalSession   = stripe.billing_portal.Session.create(
            customer    = premium_user.premium_code,
            return_url  = request.build_absolute_uri(reverse_lazy("nagoyameshi:index")),
        )

        return redirect(portalSession.url)

portal = PortalView.as_view()





# == stripe ==





class IndexView(View):

    def get(self, request, *args, **kwargs):
    
        context = {}

        # 検索フォームに、カテゴリの選択肢を作るためにも、カテゴリの全データを取り出す。
        context["categories"]   = Category.objects.all()



        #クエリを初期化しておく。
        query   = Q() 
        # この時点では検索の条件が何もない。
        # なので、 Restaurant.objects.filter(query) = Restaurant.objects.all()

        # query に検索条件を加え ↓のようにfilterの引数として使う。
        #  Restaurant.objects.filter(query)





        #検索キーワードがある場合のみ取り出す
        if "search" in request.GET:
            
            # "　A　洋食" → " A 洋食" → ["","A","洋食"]
            # "洋食　A" → "洋食 A" → [ "洋食","A" ]
            #全角スペースを半角スペースに変換、スペース区切りでリストにする。
            words   = request.GET["search"].replace("　"," ").split(" ")

            #クエリを追加する
            for word in words:

                #空欄の場合は次のループへ
                if word == "": 
                    continue

                #TIPS:AND検索の場合は&を、OR検索の場合は|を使用する。
                #query &= Q(comment__contains=word)
                query &= Q(name__contains=word)
                # 最初は query の条件は空
                # 1回目のループで、 query &= Q(name__contains="洋食")
                # 2回目のループで、 query &= Q(name__contains="A")
                # 2回目のループが終わった時点の query は？  Restaurantのnameに、『洋食を含んでいる』なおかつ『Aを含んでいる』
        """
            # 作った条件を使って検索する。
            context["restaurants"] = Restaurant.objects.filter(query)
        else:
            # 全件出す。
            context["restaurants"] = Restaurant.objects.all()
            # この時点ではqueryは空の状態
            context["restaurants"] = Restaurant.objects.filter(query)
        """

        # TODO: カテゴリ検索をする。

        if "category" in request.GET:
            if request.GET["category"] != "":
                query &= Q(category=request.GET["category"])



        # 検索している場合もしていない場合も、Restaurant.objects.filter(query) でOK
        #作ったクエリを実行(検索のパラメータがない場合、絞り込みは発動しない。)
        #context["topics"] = Topic.objects.filter(query)
        context["restaurants"] = Restaurant.objects.filter(query)
        



        #return render(request,"bbs/index.html",context)
        return render(request,"nagoyameshi/index.html",context)

# urls.pyから呼び出せるようにする
index   = IndexView.as_view()


# 店舗の個別ページを表示させるビュー
class RestaurantView(View):
    def get(self, request, pk, *args, **kwargs):
        context = {}

        # URLに含まれている整数がここで扱える。
        print(pk)

        # 店舗の個別ページなので pk( Restaurantのid)  を使って店舗検索をする。
        # .filter() で終わると、配列になってしまう。1個しかないのに配列になる。
        # .first() 配列から1番最初の要素を取る。
        context["restaurant"]   = Restaurant.objects.filter(id=pk).first()



        # レビューの全データを取り出す。全データのリスト。
        # FIXME: これでは、全店舗のレビューが表示されてしまう。
        # context["reviews"]   = Review.objects.all()
        
        # 表示する店舗に紐づくレビューだけを取る。
        context["reviews"]   = Review.objects.filter(restaurant=pk)


        # この店舗をお気に入りしたデータを全て取り出す。
        # Favorite.objects.filter(restaurant=pk)

        # 自分がお気に入りしているか？
        if request.user.is_authenticated:
            # request.userがNoneになってしまう。Noneで検索ができない。
            context["is_favorite"]   = Favorite.objects.filter(restaurant=pk,user=request.user)
        else:
            context["is_favorite"]   = False
        

        return render(request, "nagoyameshi/restaurant.html", context)

restaurant = RestaurantView.as_view()

class ReviewView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        
        #TODO: Reviewの投稿処理をする。
        print("投稿処理をする")

        #TODO: ReviewFormを使って、チェックをした上で、DBに保存する。
        form    = ReviewForm(request.POST)

        # .is_valid()でルールに従っているかチェックする。
        if form.is_valid():
            print("保存")
            form.save()
        else:
            print(form.errors)


        #TODO: 投稿処理を終えた後、トップページに移動
        # "app_name:name" で移動先のURLを与える
        return redirect("nagoyameshi:index")

review = ReviewView.as_view()


# TODO: レビューの編集をするビュー

class ReviewEditView(LoginRequiredMixin, View):

    # 編集画面を表示する
    def get(self, request, pk, *args, **kwargs):
        
        # TODO:編集するレビューを特定。
        context = {}

        # 編集する1件分のデータを特定する。1件しか無いが、これだとリスト型になってしまう。.first() 
        context["review"] = Review.objects.filter(id=pk, user=request.user).first()


        # 編集画面のページ(編集のフォーム)を表示する。 review_edit.html 
        return render(request, "nagoyameshi/review_edit.html",context)

    # 編集処理を受け付ける。
    #                       ↓ 編集したいReviewのid 
    def post(self, request, pk, *args, **kwargs):
        
        # TIPS: .filter() で終わると、結果が1件だけでもリストで出てくるので、.first() を使う。
        review = Review.objects.filter(id=pk, user=request.user).first()
        print("編集")


        # TODO: 編集処理をする。
        # バリデーションをする。ただし、編集をする場合、instance引数に編集対象のデータを指定。
        form    = ReviewForm(request.POST, instance=review)

        # instanceがないと、新規作成になってしまう。
        #form    = ReviewForm(request.POST)

        # .is_valid()でルールに従っているかチェックする。
        if form.is_valid():
            print("保存")
            form.save()
        else:
            print(form.errors)



        # 店舗の個別ページにリダイレクトさせるには？ 店舗のidが必要。reviewから取り出す。
        return redirect("nagoyameshi:restaurant", review.restaurant.id )

review_edit = ReviewEditView.as_view()

# TODO: レビューの削除をするビュー
class ReviewDeleteView(LoginRequiredMixin, View):
    #                       ↓ 削除したいReviewのid 
    def post(self, request, pk, *args, **kwargs):

        # pkを使って、Reviewから削除したいデータを取り出すには？
        # review = Review.objects.filter(id=pk)
        # ↑だと、自分が投稿していないレビューまで削除できるので、ユーザーでも絞り込みをする。
        review = Review.objects.filter(id=pk, user=request.user)

        # 削除する。
        review.delete()


        return redirect("nagoyameshi:index")

review_delete = ReviewDeleteView.as_view()




class FavoriteView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        
        # TODO: ↓ と同じものをレビューと予約の冒頭に入れる。

        # ===== リクエストを送ったユーザーが有料会員登録をしているかチェックをする =====

        premium_user = PremiumUser.objects.filter(user=request.user).first()
        

templates/nagoyameshi/mypage.html
{% extends 'nagoyameshi/base.html' %}

{% block head %}
{% load static %}

{% comment %}  
     <style>
        body{
                background-image: url("{% static 'image/fondo-web.jpg' %}");
            }
     </style>
{% endcomment %}
{% endblock %}

{% block main %}


<br><br>
<h2 class="d-inline-block text-info p-4 border border rounded-pill border-info">投稿したレビュー</h2>

{# {{ reviews }} #}

{% for review in reviews %}
<div class="border">
    <div>{{ review.restaurant.name }}</div>
    <div>{{ review.created_at }}</div>
    <div>{{ review.content }}</div>
</div>
{% endfor %}

<br>
<h2 class="d-inline-block text-info p-4 border border rounded-pill border-info">お気に入り</h2>

{% for favorite in favorites %}
<div class="border">
    <div>{{ favorite.restaurant.name }}</div>
</div>
{% endfor %}

<br>
<h2 class="d-inline-block text-info p-4 border border rounded-pill border-info">予約</h2>


{% for reservation in reservations %}
<div class="border">
    <div>{{ reservation.restaurant.name }}</div>
    <div>予約日時:{{ reservation.datetime }}</div>    
    <div>{{ reservation.headcount }}名</div> 
    

    {# TODO: 未来の予約に限り、キャンセルできるようにする。#}
    {# 予約日と今日の日付を比較する。 #}
    {% if now < reservation.datetime %}
    <form action="{% url 'nagoyameshi:reservation_cancel' reservation.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="予約キャンセル" class="d-inline-block p-2 text-danger  border rounded-bottom">
    </form>
    {% endif %}

</div>
{% endfor %}

<br><br>

{# TODO: 有料会員登録ボタンを用意する。 #}
{# 1: 有料会員登録のボタン #} 
<form action="{% url 'nagoyameshi:checkout' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="有料会員登録する - Regístrese como miembro pago">
</form>
<br>
<a href="{% url 'nagoyameshi:portal' %}"><p class="d-inline-block p-2 text-warning  border rounded-bottom">有料会員設定 - Configuración de membresía pago</p></a>




{% endblock %}

templates/nagoyameshi/restaurant.html
{% extends 'nagoyameshi/base.html' %}

{% block head %}

{% endblock %}

{% block main %}
<h2 class="text-info p-3 text-center border-bottom border-info">店舗個別ページ</h2><br>


{# 店舗1件分の表示をする。 #}
{# Mostrar una tienda. #}


{{ restaurant }}

<div>
    <h2>{{ restaurant.name }}</h2>
    <div>営業時間: {{ restaurant.start_at }} ~ {{ restaurant.end_at }}</div>
    <div>カテゴリ: {{ restaurant.category }}</div>
    <div>価格帯: {{ restaurant.cost }}円</div>
</div>


<h3 class="text-info p-5">レビュー</h3>

{# 投稿時は、POSTメソッドのリクエストで送信する。 #}
{# action: 送信するリクエストのURL、未指定の場合、このページを表示しているURLへ送信される。ReviewViewへ行くように指定 #}
{#acción: URL de la solicitud a enviar. Si no se especifica, se enviará a la URL que muestra esta página. Especifique para ir a ReviewView#}
{# method: 送信するリクエストのメソッド。postを指定 #}

<form action="{% url 'nagoyameshi:review' %}" method="post">
    {# POSTメソッドのリクエストを送る場合は、csrf_token のテンプレートタグを用意する。 #}
    {# Al enviar una solicitud de método POST, prepare una etiqueta de plantilla csrf_token. #}
    {% csrf_token %}
    {# TODO: restaurant と user のフォームも用意 #}
    <input type="hidden" name="restaurant" placeholder="店舗ID" value="{{ restaurant.id }}">
    <input type="hidden" name="user" placeholder="ユーザーID" value="{{ request.user.id }}">
    <textarea class="form-control" name="content" placeholder="レビュー内容"></textarea>
    <input type="submit" value="送信 - Enviar">
</form>
<br><br>



{# 投稿されたレビューを表示する。reviewsはリストなので、forで1つずつ取り出す。 #}

{% for review in reviews %}
<div class="border">
    <div>{{ review.created_at }}</div>
    <div>{{ review.user }}</div>
    <div>{{ review.content }}</div>
    
    {# TODO: 削除ボタンを作る (ReviewDeleteViewのpostメソッドに送信する) #}

    {# 投稿したユーザーと表示をしているユーザーが一致しているときだけ、削除ボタンを表示させる。 #}
    {% if request.user == review.user %}
    <form action="{% url 'nagoyameshi:review_delete' review.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="削除 - Eliminar" class="d-inline-block p-2 text-danger  border rounded-bottom">
    </form>

    {# 編集ページのリンクを作る #}
    <a href="{% url 'nagoyameshi:review_edit' review.id %}"><p class="d-inline-block p-2 text-warning  border rounded-bottom">編集 - Editar</p></a>


    {% endif %}

    

</div>
{% endfor %}


<h3 class="text-info p-5">お気に入り</h3>

{# FavoriteViewのpostメソッドに行く #}
<form action="{% url 'nagoyameshi:favorite' %}" method="post">
    {# POSTメソッドのリクエストを送る場合は、csrf_token のテンプレートタグを用意する。 #}
    {% csrf_token %}
    <input type="hidden" name="restaurant" placeholder="店舗ID" value="{{ restaurant.id }}">
    <input type="hidden" name="user" placeholder="ユーザーID" value="{{ request.user.id }}">   
    <input type="submit" value="お気に入りする">
</form>


<h3 class="text-info p-5">予約</h3>

<form action="{% url 'nagoyameshi:reservation' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="restaurant" placeholder="店舗ID" value="{{ restaurant.id }}">
    <input type="hidden" name="user" placeholder="ユーザーID" value="{{ request.user.id }}">   

    <input type="datetime-local" name="datetime">
    <input type="number" name="headcount" placeholder="人数">
    <input type="submit" value="予約">
</form>
<br>

{% endblock %}

templates/nagoyameshi/review_edit.html
{% extends 'nagoyameshi/base.html' %}

{% block head %}
{% endblock %}

{% block main %}

<h2>レビュー編集</h2>

{# action属性は、formの送信先のURL。 {% url 'nagoyameshi:review' %} だと、ReviewViewに行き着く。 #}
{# action属性を、ReviewEditViewに行き着くように修正をする。 #}
<form action="{% url 'nagoyameshi:review_edit' review.id %}" method="post">
    {# POSTメソッドのリクエストを送る場合は、csrf_token のテンプレートタグを用意する。 #}
    {# Al enviar una solicitud de método POST, prepare una etiqueta de plantilla csrf_token. #}
    {% csrf_token %}
    {# TODO: restaurant と user のフォームも用意 #}
    <input type="hidden" name="restaurant" placeholder="店舗ID" value="{{ review.restaurant.id }}">
    <input type="hidden" name="user" placeholder="ユーザーID" value="{{ request.user.id }}">
    <textarea class="form-control" name="content" placeholder="レビュー内容">{{ review.content }}</textarea>
    <input type="submit" value="送信 - Enviar">
</form>

{% endblock %}